#配置文件信息
runmode: debug                 # 开发模式, debug, release, test
max_ping_count: 10      #启动自连接时候的自动连接次数
url:  http://127.0.0.1:2525   # pingServer函数请求的API服务器的ip:port
port: :2525                   # 端口





#数据库
db:
  name: db_apiserver        # 数据库的名称
  addr: 47.95.5.232:3306 # 数据库的连接信息
  username: root            # 用户名
  password: 123root@A       # 密码

#docker方式的数据库连接
docker:
  name: db_apiserver        # 数据库的名称
  addr: 47.95.5.232:3306 # 数据库的连接信息
  username: root            # 用户名
  password: 123root@A       # 密码


#log
log:
  # 输出位置，有2个可选项：file,stdout。
  #选择file会将日志记录到logger_file指定的日志文件中，
  #选择stdout会将日志输出到标准输出，当然也可以两者同时选择
  writers: file,stdout
  # 日志级别，DEBUG, INFO, WARN, ,ERROR FATAL
  logger_level: DEBUG
  # 日志文件
  logger_file: log/apiserver.log
  # 日志的输出格式，json或者plaintext，
  # true会输出成非json格式,false会输出成json格式
  log_format_text: false
  # rotate依据，可选的有：daily, size。
  # 如果选daily则根据天进行转存，如果是size则根据大小进行转存
  rollingPolicy: size  #日志转存策略
  # rotate转存时间，配合rollingPolicy: daily使用
  log_rotate_date: 1
  #  rotate转存大小，配合rollingPolicy: size使用
  log_rotate_size: 1
  # 当日志文件达到转存标准时，log系统会将该日志文件进行压缩备份，这里指定了备份文件的最大个数。
  log_backup_count: 7