runmode: release                 # 开发模式, debug, release, test
addr: :1259                  # HTTP绑定端口
name: apiserver              # API Server的名字
url: http://127.0.0.1:1259   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数try的次数     # pingServer函数尝试的次数

# 是否打印grom错误日志
gormlog: false
# token 秘钥
jwt_secret: 123456
log:
  # 输出位置，有2个可选项：file,stdout。
  #选择file会将日志记录到logger_file指定的日志文件中，
  #选择stdout会将日志输出到标准输出，当然也可以两者同时选择
  writers: file,stdout
  # 日志级别，DEBUG, INFO, WARN, ,ERROR FATAL
  logger_level: DEBUG
  # 日志文件
  logger_file: log/apiserver.log
  # 日志的输出格式，json或者plaintext，
  # true会输出成非json格式,false会输出成json格式
  log_format_text: false
  # rotate依据，可选的有：daily, size。
  # 如果选daily则根据天进行转存，如果是size则根据大小进行转存
  rollingPolicy: size  #日志转存策略
  # rotate转存时间，配合rollingPolicy: daily使用
  log_rotate_date: 1
  #  rotate转存大小，配合rollingPolicy: size使用
  log_rotate_size: 1
  # 当日志文件达到转存标准时，log系统会将该日志文件进行压缩备份，这里指定了备份文件的最大个数。
  log_backup_count: 7

db:
  name: db_apiserver
  addr: 192.144.238.85:3306
  username: root
  password: 123root@A

docker_db:
  name: db_apiserver
  addr: 192.144.238.85:3306
  username: root
  password: 123root@A

